import { AGENTS } from '../config/agents.js';
import type { AnalysisResult, GeneratedArtifact, GenerationOptions } from './types';

function currentIsoDate(): string {
  return new Date().toISOString().split('T')[0];
}

function currentIsoTimestamp(): string {
  return new Date().toISOString();
}

function formatPerformanceValue(value: number | null): number | null {
  return value === null ? null : Math.round(value);
}

function sanitizeLine(value: string): string {
  return value.replace(/[\r\n]+/g, ' ').trim();
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function parseUrl(rawUrl: string): URL {
  return new URL(rawUrl);
}

function getAgentRule(options: GenerationOptions, agentId: string): 'Allow: /' | 'Disallow: /' {
  // Per-agent overrides always take precedence when explicitly set
  if (agentId in options.agents) {
    return options.agents[agentId] === false ? 'Disallow: /' : 'Allow: /';
  }

  // Fall back to profile defaults for agents not in the map
  if (options.profile === 'strict-privacy') return 'Disallow: /';
  if (options.profile === 'open-discovery') return 'Allow: /';

  if (!options.allowTraining) {
    const trainingIds = new Set(['gptbot', 'claudebot', 'bingbot', 'google-extended', 'applebot-ext']);
    if (trainingIds.has(agentId)) return 'Disallow: /';
  }

  return 'Allow: /';
}

function generateRobotsTxt(options: GenerationOptions): GeneratedArtifact {
  const parsedUrl = parseUrl(options.url);
  const sitemapUrl = sanitizeLine(new URL('/sitemap.xml', parsedUrl).href);
  const lines: string[] = [
    '# GEOforge robots.txt',
    `# Generated: ${currentIsoTimestamp()}`,
    `# Profile: ${options.profile}`,
    '',
    'User-agent: *',
    'Allow: /',
    ''
  ];

  for (const agent of AGENTS) {
    const rule = getAgentRule(options, agent.id);
    for (const ua of agent.robots) {
      lines.push(`User-agent: ${ua}`);
      lines.push(rule);
      lines.push('');
    }
  }

  if (options.includeSitemap) {
    lines.push(`Sitemap: ${sitemapUrl}`);
  }

  return { name: 'robots.txt', content: lines.join('\n'), type: 'text' };
}

function generateSitemap(options: GenerationOptions, analysis: AnalysisResult): GeneratedArtifact {
  const allUrls = [options.url, ...analysis.crawledPages];
  const unique = [...new Set(allUrls)].filter((value) => {
    try {
      new URL(value);
      return true;
    } catch {
      return false;
    }
  });

  const lines = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'];
  for (const pageUrl of unique) {
    const safeLoc = escapeXml(sanitizeLine(pageUrl));
    lines.push('  <url>');
    lines.push(`    <loc>${safeLoc}</loc>`);
    lines.push(`    <lastmod>${currentIsoDate()}</lastmod>`);
    lines.push('    <changefreq>weekly</changefreq>');
    lines.push('    <priority>0.8</priority>');
    lines.push('  </url>');
  }
  lines.push('</urlset>');

  return { name: 'sitemap.xml', content: lines.join('\n'), type: 'xml' };
}

function generateHumans(options: GenerationOptions): GeneratedArtifact {
  const year = new Date().getFullYear();
  const lines = [
    '/* TEAM */',
    'Developer: GEOforge',
    `Website: ${options.url}`,
    `Generated: ${currentIsoDate()}`,
    '',
    '/* SITE */',
    `Last update: ${year}`,
    'Standards: HTML5, CSS3, JavaScript',
    'Software: GEOforge'
  ];

  return { name: 'humans.txt', content: lines.join('\n'), type: 'text' };
}

function generateAiTxt(options: GenerationOptions, analysis: AnalysisResult): GeneratedArtifact {
  const domain = sanitizeLine(parseUrl(options.url).hostname);
  const lines = [
    `# AI Interaction Guidelines for ${domain}`,
    '# Generated by GEOforge',
    `# Updated: ${currentIsoTimestamp()}`,
    '',
    `training: ${options.profile === 'strict-privacy' || !options.allowTraining ? 'disallowed' : 'allowed'}`,
    'crawling: allowed',
    'attribution: required',
    `language: ${analysis.metadata.language || 'en'}`
  ];

  return { name: '.well-known/ai.txt', content: lines.join('\n'), type: 'text' };
}

function generateSecurityTxt(options: GenerationOptions): GeneratedArtifact {
  const domain = sanitizeLine(parseUrl(options.url).hostname);
  const expires = new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString();

  return {
    name: '.well-known/security.txt',
    content: [
      `Contact: mailto:security@${domain}`,
      `Expires: ${expires}`,
      'Preferred-Languages: en',
      `Canonical: https://${domain}/.well-known/security.txt`
    ].join('\n'),
    type: 'text'
  };
}

function generateManifest(options: GenerationOptions, analysis: AnalysisResult): GeneratedArtifact {
  const siteTitle = sanitizeLine(analysis.metadata.title || options.siteName || parseUrl(options.url).hostname);
  return {
    name: 'manifest.json',
    type: 'json',
    content: JSON.stringify(
      {
        name: siteTitle,
        short_name: siteTitle.split(' ')[0],
        description: analysis.metadata.description || `AI optimization files for ${siteTitle}`,
        start_url: '/',
        display: 'standalone',
        background_color: '#ffffff',
        theme_color: '#D4AF37'
      },
      null,
      2
    )
  };
}

function generateBrowserConfig(): GeneratedArtifact {
  return {
    name: 'browserconfig.xml',
    type: 'xml',
    content: `<?xml version="1.0" encoding="utf-8"?>\n<browserconfig>\n  <msapplication>\n    <tile>\n      <TileColor>#D4AF37</TileColor>\n    </tile>\n  </msapplication>\n</browserconfig>`
  };
}

function generateAds(options: GenerationOptions): GeneratedArtifact[] {
  const domain = sanitizeLine(parseUrl(options.url).hostname);
  return [
    {
      name: 'ads.txt',
      type: 'text',
      content: `# ads.txt for ${domain}\n# Add authorized sellers here.`
    },
    {
      name: 'app-ads.txt',
      type: 'text',
      content: `# app-ads.txt for ${domain}\n# Add authorized app sellers here.`
    }
  ];
}

function generateReport(options: GenerationOptions, analysis: AnalysisResult): GeneratedArtifact {
  const report = {
    geoforge: {
      generated: currentIsoTimestamp(),
      profile: options.profile,
      url: options.url
    },
    site: analysis.metadata,
    technical: analysis.technical,
    performance: {
      loadTime: formatPerformanceValue(analysis.performance.loadTime),
      domContentLoaded: formatPerformanceValue(analysis.performance.domContentLoaded),
      firstContentfulPaint: formatPerformanceValue(analysis.performance.firstContentfulPaint),
      largestContentfulPaint: formatPerformanceValue(analysis.performance.largestContentfulPaint),
      cumulativeLayoutShift: analysis.performance.cumulativeLayoutShift,
      firstInputDelay: formatPerformanceValue(analysis.performance.firstInputDelay)
    },
    summary: {
      links: analysis.seo.links.length,
      images: analysis.seo.images.length,
      stylesheets: analysis.assets.stylesheets.length,
      scripts: analysis.assets.scripts.length,
      hasRobots: analysis.technical.hasRobots,
      hasSitemap: analysis.technical.hasSitemap
    }
  };

  return { name: 'geoforge.json', content: JSON.stringify(report, null, 2), type: 'json' };
}

export function generateArtifacts(options: GenerationOptions, analysis: AnalysisResult): GeneratedArtifact[] {
  const artifacts: GeneratedArtifact[] = [generateRobotsTxt(options)];

  if (options.includeSitemap) artifacts.push(generateSitemap(options, analysis));
  if (options.includeHumans) artifacts.push(generateHumans(options));
  if (options.includeAiTxt) artifacts.push(generateAiTxt(options, analysis));
  if (options.includeSecurityTxt) artifacts.push(generateSecurityTxt(options));
  if (options.includeManifest) artifacts.push(generateManifest(options, analysis), generateBrowserConfig());
  if (options.includeAds) artifacts.push(...generateAds(options));
  artifacts.push(generateReport(options, analysis));

  return artifacts;
}
