import type { AnalysisResult } from '../cliWebsiteAnalyzer.js';

export function generateHumansTxt(url: string, analysis: AnalysisResult): string {
  const domain = new URL(url).hostname;
  const year = new Date().getFullYear();
  const siteTitle = analysis.metadata.title || domain;
  
  return `/* TEAM */
    Developer: Generated by GEOforge CLI
    Contact: Generated for ${domain}
    Site: ${siteTitle}

/* SITE */
    Last update: ${year}/08/04
    Language: ${analysis.metadata.language || 'English'}
    Doctype: HTML5
    IDE: Visual Studio Code
    Standards: HTML5, CSS3, JavaScript ES6+
    Components: React, TypeScript, Vite, Tailwind CSS
    Software: Node.js, npm, Git

/* PURPOSE */
    Generate AI-optimized website files for maximum Generative Engine Optimization (GEO)
    Create robots.txt, sitemaps, and vendor-specific AI manifests
    Enable websites to be easily discovered and indexed by AI crawlers and LLMs

/* MISSION */
    Democratize AI website optimization
    Make GEO accessible to all developers
    Bridge the gap between traditional SEO and AI discovery

/* VALUES */
    Open Source: Transparency and collaboration
    Innovation: Cutting-edge AI optimization techniques
    Accessibility: Tools for everyone, regardless of technical expertise
    Community: Supporting the broader AI and web development ecosystem

/* TECHNOLOGY */
    Frontend: React 18, TypeScript, Vite
    Styling: Tailwind CSS, CSS3
    Build: Vite, npm
    Deployment: Netlify, GitHub Pages
    Version Control: Git, GitHub
    Code Quality: ESLint, Prettier

/* AI PLATFORMS SUPPORTED */
    GPTBot (OpenAI)
    ClaudeBot (Anthropic)
    Bingbot (Microsoft)
    Google-Extended (Google)
    Applebot-Extended (Apple)
    PerplexityBot (Perplexity)
    CCBot (Common Crawl)
    YouBot (You.com)
    CohereBot (Cohere)
    AI21Bot (AI21)
    HuggingFaceBot (Hugging Face)
    StabilityBot (Stability AI)
    MidjourneyBot (Midjourney)
    DALL-E-Bot (OpenAI)
    BardBot (Google)
    GeminiBot (Google)
    CopilotBot (Microsoft)
    SGEBot (Google)
    ResearchBot (Various)
    AcademicBot (Academic)
    ScholarBot (Academic)
    ArXivBot (ArXiv)
    PubMedBot (PubMed)
    EnterpriseBot (Enterprise)
    BusinessBot (Business)
    CorporateBot (Corporate)
    AIBot (Generic)
    MLBot (Machine Learning)
    NeuralBot (Neural Networks)
    DeepLearningBot (Deep Learning)
    LLMBot (Large Language Models)
    GenAIBot (Generative AI)
    AGIBot (Artificial General Intelligence)

/* GENERATED FILES */
    robots.txt: AI crawler directives
    sitemap.xml: Site structure for crawlers
    sitemap.json: JSON sitemap for AI crawlers
    ai.txt: AI interaction guidelines
    security.txt: Security contact information
    humans.txt: Human-readable project information
    manifest.json: PWA manifest
    browserconfig.xml: Microsoft tile configuration
    ads.txt: Authorized digital sellers
    app-ads.txt: Mobile app advertising


/* CONTRIBUTING */
    We welcome contributions! See CONTRIBUTING.md for guidelines.
    Report bugs, suggest features, or submit pull requests.
    Join our community of AI optimization enthusiasts.

/* LICENSE */
    MIT License - See LICENSE file for details
    Open source and free to use, modify, and distribute

/* THANKS */
    OpenAI for GPTBot and AI crawler standards
    Anthropic for ClaudeBot and AI safety
    Google for search and AI integration
    Microsoft for Bing and AI services
    Apple for Applebot and privacy-focused AI
    All AI crawler developers and researchers
    The open source community
    Contributors and users of GEOforge

/* INSPIRATION */
    The need for AI-optimized websites
    Growing importance of Generative Engine Optimization
    Desire to make AI discovery accessible to all
    Passion for open source and community-driven development`;
} 