import type { AnalysisResult } from '../cliWebsiteAnalyzer.js';

export function generateAdsTxt(url: string, analysis: AnalysisResult): string {
  const domain = new URL(url).hostname;
  
  return `# Ads.txt file for ${domain}
# Generated by GEOforge CLI
# This file lists authorized digital sellers for your domain

# Example entries (replace with your actual authorized sellers)
# google.com, pub-0000000000000000, DIRECT, f08c47fec0942fa0
# amazon.com, pub-0000000000000000, RESELLER, f08c47fec0942fa0

# For more information, visit: https://iabtechlab.com/ads-txt/`;
}

export function generateAppAdsTxt(url: string, analysis: AnalysisResult): string {
  const domain = new URL(url).hostname;
  
  return `# App-ads.txt file for ${domain}
# Generated by GEOforge CLI
# This file lists authorized digital sellers for your mobile apps

# Example entries (replace with your actual authorized sellers)
# google.com, pub-0000000000000000, DIRECT, f08c47fec0942fa0
# amazon.com, pub-0000000000000000, RESELLER, f08c47fec0942fa0

# For more information, visit: https://iabtechlab.com/app-ads-txt/`;
} 